### ISSUE TITLE
Wallet won't sync

### ISSUE THREAD

**Issue by peterzxzx** [SirElven8/NestEGG#1]
The new 1.2 wallet don't find any connections, so my wallet won't sync, and can't start my masternode

**Comment by shamimiceewu025** [comment]
It may be banned ip or network communication issue, please do run below comand  

clearbanned 


Also, as you do update , please go to your Settings -> Dubes -> repair wallet 
Then Resync wallet

**Comment by peterzxzx** [comment]
Ok, 

so I did the clearbanned

and in the wallet repair tab, did the:
- salvage wallet
- rescan blockchain file
- upgrade wallet format

but I still can't get connections to sync, have 1 connection for 2 seconds, the 0 connections, then 1 connection for 2-4 seconds, then 0 again.

: (

**Comment by shamimiceewu025** [comment]
and in the wallet repair tab, did the:

   resync blockchain file .

This resolve This Issue. Also, Further Update we add more seednode . Thus easily This Issue Resolved

**Comment by shamimiceewu025** [comment]
use Recommended  latest Release . Here we fixed Seednode Issue

**Comment by peterzxzx** [comment]
I did the rescan block file, still not working, I have the previous seed nodes in the config file.

**Comment by shamimiceewu025** [comment]
Not rescan . do "Delete local blockchain" this option.

**Comment by Dum0l-R1kl0-Pr0h1p** [comment]
Still can't sync

**Comment by peterzxzx** [comment]
Mine is working now, have 4 active connections, everything synced and running as supposed to

**Comment by shamimiceewu025** [comment]
@Dum0l-R1kl0-Pr0h1p  follow Instruction as previous User .
